-- Finance module tables and RLS policies.
-- Consolidated from apps/backend/src/main/java/com/xqt/saas/finance/sql/*.sql
-- Idempotent: all DDL uses CREATE TABLE IF NOT EXISTS / CREATE OR REPLACE.

-- ──────────────────────────────────────────────────────────────────────────────
-- Shared trigger function (update_time auto-maintenance)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_modified_column()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_fee_type
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_fee_type
(
    id          bigint generated by default as identity PRIMARY KEY,
    tenant_id   uuid    NOT NULL,
    code        text,
    name        text,
    type        text,
    price       DECIMAL(10, 2),
    is_show     BOOLEAN,
    create_by   text                     DEFAULT 'admin',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by   text                     DEFAULT 'admin',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_fee_type IS '费用类型';
CREATE TRIGGER trigger_finance_fee_type_update_time
    BEFORE UPDATE ON finance_fee_type
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_monthly_statement
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_monthly_statement
(
    id             bigint generated by default as identity PRIMARY KEY,
    tenant_id      uuid NOT NULL,
    start_time     TIMESTAMP WITHOUT TIME ZONE,
    end_time       TIMESTAMP WITHOUT TIME ZONE,
    receivable     BOOLEAN,
    payable        BOOLEAN,
    sales_cost     BOOLEAN,
    waybill        BOOLEAN,
    bill_of_lading BOOLEAN,
    remark         text,
    create_by      text                     DEFAULT 'admin',
    create_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by      text                     DEFAULT 'admin',
    update_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_monthly_statement IS '月结单';
CREATE TRIGGER trigger_finance_monthly_statement_update_time
    BEFORE UPDATE ON finance_monthly_statement
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_account
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_account
(
    id           bigint generated by default as identity PRIMARY KEY,
    tenant_id    uuid         NOT NULL,
    account_name text         NOT NULL,
    currency     text,
    balance      DECIMAL(18, 4) DEFAULT 0,
    bank_name    text,
    type         smallint     NOT NULL,
    visible      BOOLEAN        DEFAULT true,
    remark       text,
    create_by    text                     DEFAULT 'admin',
    create_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by    text                     DEFAULT 'admin',
    update_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_account IS '账户表';
COMMENT ON COLUMN finance_account.type IS '1.公司 2.客户 3.供应商 4.员工';
CREATE TRIGGER trigger_finance_account_update_time
    BEFORE UPDATE ON finance_account
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_account_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_account_transaction
(
    id               bigint generated by default as identity PRIMARY KEY,
    tenant_id        uuid NOT NULL,
    transaction_no   text,
    account_id       bigint,
    customer_id      bigint,
    transaction_type smallint,
    currency         text,
    amount           DECIMAL(18, 4),
    fee              DECIMAL(18, 4),
    credit_amount    DECIMAL(18, 4),
    remark           text,
    payment_time     TIMESTAMP WITHOUT TIME ZONE,
    create_by        text                     DEFAULT 'admin',
    create_time      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by        text                     DEFAULT 'admin',
    update_time      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_account_transaction IS '账户流水表';
COMMENT ON COLUMN finance_account_transaction.transaction_type IS '1.公司 2.客户 3.供应商 4.员工';
CREATE TRIGGER trigger_finance_account_transaction_update_time
    BEFORE UPDATE ON finance_account_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_sales_commission
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_sales_commission
(
    id                bigint generated by default as identity PRIMARY KEY,
    tenant_id         uuid NOT NULL,
    commission_no     text,
    sales             text,
    currency          text,
    commission_amount DECIMAL(18, 4),
    status            smallint,
    paid              DECIMAL(18, 4),
    balance           DECIMAL(18, 4),
    remark            text,
    bill_date         TIMESTAMP WITHOUT TIME ZONE,
    due_date          TIMESTAMP WITHOUT TIME ZONE,
    audit_time        TIMESTAMP WITHOUT TIME ZONE,
    create_by         text                     DEFAULT 'admin',
    create_time       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by         text                     DEFAULT 'admin',
    update_time       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_sales_commission IS '销售提成单表';
COMMENT ON COLUMN finance_sales_commission.status IS '1.待审核 2.已审核 3.已发放';
CREATE TRIGGER trigger_finance_sales_commission_update_time
    BEFORE UPDATE ON finance_sales_commission
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_sales_commission_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_sales_commission_transaction
(
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          uuid NOT NULL,
    transaction_no     text,
    sales              text,
    commission_no      text,
    waybill_no         text,
    fee_type           text,
    fee                DECIMAL(18, 4),
    exchange_rate      DECIMAL(10, 4),
    local_currency_fee DECIMAL(18, 4),
    audit_status       smallint,
    remark             text,
    business_time      TIMESTAMP WITHOUT TIME ZONE,
    create_by          text                     DEFAULT 'admin',
    create_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by          text                     DEFAULT 'admin',
    update_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_sales_commission_transaction IS '销售提成流水表';
COMMENT ON COLUMN finance_sales_commission_transaction.audit_status IS '1.待审计 2.已审计';
CREATE TRIGGER trigger_finance_sales_commission_transaction_update_time
    BEFORE UPDATE ON finance_sales_commission_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_sales_cost_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_sales_cost_transaction
(
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          uuid NOT NULL,
    transaction_no     text,
    employee           text,
    waybill_no         text,
    transfer_no        text,
    fee_type           text,
    fee                DECIMAL(18, 4),
    exchange_rate      DECIMAL(10, 4),
    local_currency_fee DECIMAL(18, 4),
    audit_status       smallint,
    remark             text,
    business_time      TIMESTAMP WITHOUT TIME ZONE,
    create_by          text                     DEFAULT 'admin',
    create_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by          text                     DEFAULT 'admin',
    update_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_sales_cost_transaction IS '销售成本流水表';
COMMENT ON COLUMN finance_sales_cost_transaction.audit_status IS '1.待审计 2.已审计';
CREATE TRIGGER trigger_finance_sales_cost_transaction_update_time
    BEFORE UPDATE ON finance_sales_cost_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_supplier_bill
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_supplier_bill
(
    id                bigint generated by default as identity PRIMARY KEY,
    tenant_id         uuid NOT NULL,
    bill_no           text,
    supplier          text,
    currency          text,
    status            smallint,
    transaction_total DECIMAL(18, 4),
    bill_amount       DECIMAL(18, 4),
    custom_flag       text,
    bill_date         TIMESTAMP WITHOUT TIME ZONE,
    due_date          TIMESTAMP WITHOUT TIME ZONE,
    write_off_time    TIMESTAMP WITHOUT TIME ZONE,
    create_by         text                     DEFAULT 'admin',
    create_time       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by         text                     DEFAULT 'admin',
    update_time       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_supplier_bill IS '供应商账单表';
COMMENT ON COLUMN finance_supplier_bill.status IS '1.待审核 2.待核销 3.已核销';
CREATE TRIGGER trigger_finance_supplier_bill_update_time
    BEFORE UPDATE ON finance_supplier_bill
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_supplier_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_supplier_transaction
(
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          uuid NOT NULL,
    transaction_no     text,
    supplier           text,
    bill_no            text,
    waybill_no         text,
    waybill_sales      text,
    bill_of_lading_no  text,
    transfer_no        text,
    fee_type           text,
    quantity           DECIMAL(10, 2),
    fee                DECIMAL(18, 4),
    exchange_rate      DECIMAL(10, 4),
    local_currency_fee DECIMAL(18, 4),
    audit_status       smallint,
    write_off_status   smallint,
    custom_flag        text,
    write_off_time     TIMESTAMP WITHOUT TIME ZONE,
    business_time      TIMESTAMP WITHOUT TIME ZONE,
    create_by          text                     DEFAULT 'admin',
    create_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by          text                     DEFAULT 'admin',
    update_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_supplier_transaction IS '供应商流水表';
COMMENT ON COLUMN finance_supplier_transaction.audit_status IS '1.待审计 2.已审计';
COMMENT ON COLUMN finance_supplier_transaction.write_off_status IS '1.待核销 2.已核销';
CREATE TRIGGER trigger_finance_supplier_transaction_update_time
    BEFORE UPDATE ON finance_supplier_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_customer_bill
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_customer_bill
(
    id                   bigint generated by default as identity PRIMARY KEY,
    tenant_id            uuid NOT NULL,
    bill_no              text,
    user_settle          text,
    branch_company       text,
    currency             text,
    bill_amount          DECIMAL(18, 4),
    paid_amount          DECIMAL(18, 4),
    remaining_amount     DECIMAL(18, 4),
    sales_rep            text,
    customer_service_rep text,
    finance_rep          text,
    due_action           text,
    bill_confirmed       BOOLEAN DEFAULT false,
    status               smallint,
    bill_date            TIMESTAMP WITHOUT TIME ZONE,
    due_date             TIMESTAMP WITHOUT TIME ZONE,
    write_off_time       TIMESTAMP WITHOUT TIME ZONE,
    create_by            text                     DEFAULT 'admin',
    create_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by            text                     DEFAULT 'admin',
    update_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_customer_bill IS '客户账单表';
COMMENT ON COLUMN finance_customer_bill.status IS '1.待审核 2.待核销 3.已核销';
CREATE TRIGGER trigger_finance_customer_bill_update_time
    BEFORE UPDATE ON finance_customer_bill
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_customer_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_customer_transaction
(
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          uuid NOT NULL,
    transaction_no     text,
    user_name          text,
    user_sales_rep     text,
    bill_no            text,
    waybill_no         text,
    bill_of_lading_no  text,
    transfer_no        text,
    order_no           text,
    service            text,
    fee_type           text,
    quantity           DECIMAL(10, 2),
    fee                DECIMAL(18, 4),
    exchange_rate      DECIMAL(10, 4),
    local_currency_fee DECIMAL(18, 4),
    audit_status       smallint,
    write_off_status   smallint,
    approval_status    smallint,
    approver           text,
    custom_flag        text,
    remark             text,
    write_off_time     TIMESTAMP WITHOUT TIME ZONE,
    business_time      TIMESTAMP WITHOUT TIME ZONE,
    create_by          text                     DEFAULT 'admin',
    create_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by          text                     DEFAULT 'admin',
    update_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_customer_transaction IS '客户流水表';
COMMENT ON COLUMN finance_customer_transaction.audit_status IS '1.待审计 2.已审计';
COMMENT ON COLUMN finance_customer_transaction.write_off_status IS '1.待核销 2.已核销';
CREATE TRIGGER trigger_finance_customer_transaction_update_time
    BEFORE UPDATE ON finance_customer_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_price_maintenance
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_price_maintenance
(
    id           bigint generated by default as identity PRIMARY KEY,
    tenant_id    uuid NOT NULL,
    name         text,
    service      text,
    receive_area text,
    priority     integer,
    user_level   text,
    user_name    text,
    min_weight   DECIMAL(10, 2),
    max_weight   DECIMAL(10, 2),
    zip_prefix   text,
    parent_id    bigint,
    status       BOOLEAN DEFAULT true,
    price_type   smallint,
    create_by    text                     DEFAULT 'admin',
    create_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by    text                     DEFAULT 'admin',
    update_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_price_maintenance IS '运价维护表';
COMMENT ON COLUMN finance_price_maintenance.price_type IS '1.公布价 2.销售员底价 3.成本价';
CREATE TRIGGER trigger_finance_price_maintenance_update_time
    BEFORE UPDATE ON finance_price_maintenance
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_payable_report
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_payable_report
(
    id                   bigint generated by default as identity PRIMARY KEY,
    tenant_id            uuid NOT NULL,
    user_name            text,
    currency             text,
    turnover             DECIMAL(18, 4),
    paid_amount          DECIMAL(18, 4),
    pending_amount       DECIMAL(18, 4),
    issued_bill          DECIMAL(18, 4),
    pending_bill         DECIMAL(18, 4),
    paid_bill            DECIMAL(18, 4),
    pending_payment_bill DECIMAL(18, 4),
    create_by            text                     DEFAULT 'admin',
    create_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by            text                     DEFAULT 'admin',
    update_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_payable_report IS '应付报表表';
CREATE TRIGGER trigger_finance_payable_report_update_time
    BEFORE UPDATE ON finance_payable_report
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_receivable_report
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_receivable_report
(
    id                   bigint generated by default as identity PRIMARY KEY,
    tenant_id            uuid NOT NULL,
    user_name            text,
    currency             text,
    turnover             DECIMAL(18, 4),
    paid_amount          DECIMAL(18, 4),
    pending_amount       DECIMAL(18, 4),
    issued_bill          DECIMAL(18, 4),
    pending_bill         DECIMAL(18, 4),
    paid_bill            DECIMAL(18, 4),
    pending_payment_bill DECIMAL(18, 4),
    actual_amount        DECIMAL(18, 4),
    customer_service_rep text,
    sales_rep            text,
    finance_rep          text,
    settlement_method    text,
    user_level           text,
    user_remark          text,
    create_by            text                     DEFAULT 'admin',
    create_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by            text                     DEFAULT 'admin',
    update_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_receivable_report IS '应收报表表';
CREATE TRIGGER trigger_finance_receivable_report_update_time
    BEFORE UPDATE ON finance_receivable_report
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_waybill_audit
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_waybill_audit
(
    id                   bigint generated by default as identity PRIMARY KEY,
    tenant_id            uuid NOT NULL,
    waybill_no           text,
    user_name            text,
    service              text,
    country              text,
    piece_count          integer,
    actual_weight        DECIMAL(10, 2),
    volume_weight        DECIMAL(10, 2),
    charge_weight        DECIMAL(10, 2),
    supplier_weight      DECIMAL(10, 2),
    status               smallint,
    receivable_amount    DECIMAL(18, 4),
    payable_amount       DECIMAL(18, 4),
    sales_cost           DECIMAL(18, 4),
    sales_commission     DECIMAL(18, 4),
    gross_profit         DECIMAL(18, 4),
    customer_service_rep text,
    sales_rep            text,
    picking_time         TIMESTAMP WITHOUT TIME ZONE,
    create_by            text                     DEFAULT 'admin',
    create_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by            text                     DEFAULT 'admin',
    update_time          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_waybill_audit IS '运单审计表';
COMMENT ON COLUMN finance_waybill_audit.status IS '1已收货 2转运中 3已签收 4退件';
CREATE TRIGGER trigger_finance_waybill_audit_update_time
    BEFORE UPDATE ON finance_waybill_audit
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_transaction
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_transaction
(
    id                    bigint generated by default as identity PRIMARY KEY,
    tenant_id             uuid NOT NULL,
    transaction_no        text,
    user_name             text,
    company_account       text,
    user_account          text,
    currency              text,
    amount                DECIMAL(18, 4),
    fee                   DECIMAL(18, 4),
    type                  smallint,
    audit_transaction_no  text,
    payment_status        smallint,
    invoiced              BOOLEAN DEFAULT false,
    bill_no               text,
    audit_time            TIMESTAMP WITHOUT TIME ZONE,
    payment_time          TIMESTAMP WITHOUT TIME ZONE,
    create_by             text                     DEFAULT 'admin',
    create_time           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_by             text                     DEFAULT 'admin',
    update_time           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE finance_transaction IS '财务流水表';
COMMENT ON COLUMN finance_transaction.type IS '1客户充值 2客户提现 3支付供应商 4供应商退款 5经营收入 6经营支出 7工资发放 8提成发放 9内部转账';
CREATE TRIGGER trigger_finance_transaction_update_time
    BEFORE UPDATE ON finance_transaction
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_approval
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_approval
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            uuid        NOT NULL,
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL,
    created_by           TEXT        NOT NULL,
    updated_by           TEXT        NOT NULL,
    type                 TEXT,
    associate_order_id   TEXT,
    associate_order_user TEXT,
    reason               TEXT,
    fee_type             TEXT,
    fee_amount           DOUBLE PRECISION,
    modifier             DOUBLE PRECISION,
    bubble_modifier      DOUBLE PRECISION,
    approver             TEXT,
    applicant            TEXT,
    approval_status      TEXT,
    approval_reason      TEXT,
    pay_status           TEXT,
    happened_at          timestamptz
);
COMMENT ON TABLE finance_approval IS '审批表';

-- ──────────────────────────────────────────────────────────────────────────────
-- finance_currency + finance_currency_exchange
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_currency
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  uuid        NOT NULL,
    created_at timestamptz NOT NULL,
    created_by TEXT        NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by TEXT        NOT NULL,
    code       TEXT        NOT NULL UNIQUE,
    name       TEXT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_finance_currency_code ON finance_currency (code);
COMMENT ON TABLE finance_currency IS '货币';

CREATE TABLE IF NOT EXISTS finance_currency_exchange
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            uuid           NOT NULL,
    created_at           timestamptz    NOT NULL,
    created_by           TEXT           NOT NULL,
    updated_at           timestamptz    NOT NULL,
    updated_by           TEXT           NOT NULL,
    code                 TEXT           NOT NULL REFERENCES finance_currency (code),
    application_scenario TEXT           NOT NULL CHECK (application_scenario IN ('应收', '应付')),
    rate                 NUMERIC(18, 8) NOT NULL,
    effective_from       timestamptz    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_finance_currency_exchange_unique
    ON finance_currency_exchange (code, application_scenario, effective_from);
COMMENT ON TABLE finance_currency_exchange IS '货币的汇率记录';
COMMENT ON COLUMN finance_currency_exchange.application_scenario IS '应用场景：应收/应付';

-- ──────────────────────────────────────────────────────────────────────────────
-- RLS policies  (RISK-2)
-- All 19 finance tables use app_tenant_matches() defined in 002_rls.sql.
-- ──────────────────────────────────────────────────────────────────────────────
ALTER TABLE finance_fee_type                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_fee_type                   FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_fee_type_tenant_isolation ON finance_fee_type
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_monthly_statement          ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_monthly_statement          FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_monthly_statement_tenant_isolation ON finance_monthly_statement
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_account                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_account                    FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_account_tenant_isolation ON finance_account
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_account_transaction        ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_account_transaction        FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_account_transaction_tenant_isolation ON finance_account_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_sales_commission           ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_sales_commission           FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_sales_commission_tenant_isolation ON finance_sales_commission
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_sales_commission_transaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_sales_commission_transaction FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_sales_commission_transaction_tenant_isolation ON finance_sales_commission_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_sales_cost_transaction     ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_sales_cost_transaction     FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_sales_cost_transaction_tenant_isolation ON finance_sales_cost_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_supplier_bill              ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_supplier_bill              FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_supplier_bill_tenant_isolation ON finance_supplier_bill
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_supplier_transaction       ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_supplier_transaction       FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_supplier_transaction_tenant_isolation ON finance_supplier_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_customer_bill              ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_customer_bill              FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_customer_bill_tenant_isolation ON finance_customer_bill
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_customer_transaction       ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_customer_transaction       FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_customer_transaction_tenant_isolation ON finance_customer_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_price_maintenance          ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_price_maintenance          FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_price_maintenance_tenant_isolation ON finance_price_maintenance
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_payable_report             ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_payable_report             FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_payable_report_tenant_isolation ON finance_payable_report
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_receivable_report          ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_receivable_report          FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_receivable_report_tenant_isolation ON finance_receivable_report
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_waybill_audit              ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_waybill_audit              FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_waybill_audit_tenant_isolation ON finance_waybill_audit
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_transaction                ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_transaction                FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_transaction_tenant_isolation ON finance_transaction
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_approval                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_approval                   FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_approval_tenant_isolation ON finance_approval
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_currency                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_currency                   FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_currency_tenant_isolation ON finance_currency
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));

ALTER TABLE finance_currency_exchange          ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_currency_exchange          FORCE  ROW LEVEL SECURITY;
CREATE POLICY finance_currency_exchange_tenant_isolation ON finance_currency_exchange
    USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id));
