-- 建表
CREATE TABLE IF NOT EXISTS finance_fee_type
(
    id          bigint generated by default as identity PRIMARY KEY,   -- 自增主键，等价于 int auto_increment
    tenant_id   uuid not null,                                           -- 租户ID
    code        text,                                                  -- 代码
    name        text,                                                  -- 名称
    type        text,                                                  -- 类型
    price       DECIMAL(10, 2),                                        -- 价格
    is_show     BOOLEAN,                                               -- 是否显示（原 tinyint(1) 转为 boolean）
    create_by   text DEFAULT 'admin',                                  -- 创建者
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    update_by   text DEFAULT 'admin',                                  -- 更新者
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP  -- 更新时间
);

-- 表注释
COMMENT ON TABLE finance_fee_type IS '费用类型';

-- 列注释
COMMENT ON COLUMN finance_fee_type.id IS '主键ID';
COMMENT ON COLUMN finance_fee_type.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_fee_type.code IS '代码';
COMMENT ON COLUMN finance_fee_type.name IS '名称';
COMMENT ON COLUMN finance_fee_type.type IS '类型';
COMMENT ON COLUMN finance_fee_type.price IS '价格';
COMMENT ON COLUMN finance_fee_type.is_show IS '是否显示';
COMMENT ON COLUMN finance_fee_type.create_by IS '创建者';
COMMENT ON COLUMN finance_fee_type.create_time IS '创建时间';
COMMENT ON COLUMN finance_fee_type.update_by IS '更新者';
COMMENT ON COLUMN finance_fee_type.update_time IS '更新时间';

-- 触发器函数：更新时自动设置 update_time 为当前时间
CREATE OR
REPLACE FUNCTION update_modified_column()
    RETURNS TRIGGER AS
$$
BEGIN NEW.update_time = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 在 finance_fee_type 上创建 BEFORE UPDATE 触发器
CREATE TRIGGER trigger_finance_fee_type_update_time
    BEFORE UPDATE
    ON finance_fee_type
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

SELECT set_config('app.service_role', 'true', false);

SELECT id, username, email, tenant_id, status, password_hash
FROM users
LIMIT 50;

