CREATE TABLE IF NOT EXISTS finance_supplier_bill
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    bill_no         text,                                                    -- 单号
    supplier        text,                                                    -- 供应商
    currency        text,                                                    -- 币种
    status          smallint,                                                -- 状态：1.待审核 2.待核销 3.已核销
    transaction_total decimal(18,4),                                        -- 流水总额
    bill_amount     decimal(18,4),                                           -- 账单金额
    custom_flag     text,                                                    -- 自定义标识
    bill_date       TIMESTAMP WITHOUT TIME ZONE,                             -- 账单日期
    due_date        TIMESTAMP WITHOUT TIME ZONE,                             -- 到期时间
    write_off_time  TIMESTAMP WITHOUT TIME ZONE,                             -- 核销时间
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_supplier_bill IS '供应商账单表';

COMMENT ON COLUMN finance_supplier_bill.id IS '主键ID';
COMMENT ON COLUMN finance_supplier_bill.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_supplier_bill.bill_no IS '单号';
COMMENT ON COLUMN finance_supplier_bill.supplier IS '供应商';
COMMENT ON COLUMN finance_supplier_bill.currency IS '币种';
COMMENT ON COLUMN finance_supplier_bill.status IS '状态：1.待审核 2.待核销 3.已核销';
COMMENT ON COLUMN finance_supplier_bill.transaction_total IS '流水总额';
COMMENT ON COLUMN finance_supplier_bill.bill_amount IS '账单金额';
COMMENT ON COLUMN finance_supplier_bill.custom_flag IS '自定义标识';
COMMENT ON COLUMN finance_supplier_bill.bill_date IS '账单日期';
COMMENT ON COLUMN finance_supplier_bill.due_date IS '到期时间';
COMMENT ON COLUMN finance_supplier_bill.write_off_time IS '核销时间';
COMMENT ON COLUMN finance_supplier_bill.create_by IS '创建者';
COMMENT ON COLUMN finance_supplier_bill.create_time IS '创建时间';
COMMENT ON COLUMN finance_supplier_bill.update_by IS '更新者';
COMMENT ON COLUMN finance_supplier_bill.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_supplier_bill_update_time
    BEFORE UPDATE
    ON finance_supplier_bill
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_supplier_transaction
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    transaction_no      text,                                                    -- 流水号
    supplier            text,                                                    -- 供应商
    bill_no             text,                                                    -- 账单
    waybill_no          text,                                                    -- 运单号
    waybill_sales       text,                                                    -- 运单销售代表
    bill_of_lading_no   text,                                                    -- 提单号
    transfer_no         text,                                                    -- 转单号
    fee_type            text,                                                    -- 费用类型
    quantity            decimal(10,2),                                           -- 数量
    fee                 decimal(18,4),                                           -- 费用
    exchange_rate       decimal(10,4),                                           -- 汇率
    local_currency_fee  decimal(18,4),                                           -- 本币费用
    audit_status        smallint,                                                -- 审核：1.待审计 2.已审计
    write_off_status    smallint,                                                -- 核销：1.待核销 2.已核销
    custom_flag         text,                                                    -- 自定义标识
    write_off_time      TIMESTAMP WITHOUT TIME ZONE,                             -- 核销时间
    business_time       TIMESTAMP WITHOUT TIME ZONE,                             -- 业务时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_supplier_transaction IS '供应商流水表';

COMMENT ON COLUMN finance_supplier_transaction.id IS '主键ID';
COMMENT ON COLUMN finance_supplier_transaction.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_supplier_transaction.transaction_no IS '流水号';
COMMENT ON COLUMN finance_supplier_transaction.supplier IS '供应商';
COMMENT ON COLUMN finance_supplier_transaction.bill_no IS '账单';
COMMENT ON COLUMN finance_supplier_transaction.waybill_no IS '运单号';
COMMENT ON COLUMN finance_supplier_transaction.waybill_sales IS '运单销售代表';
COMMENT ON COLUMN finance_supplier_transaction.bill_of_lading_no IS '提单号';
COMMENT ON COLUMN finance_supplier_transaction.transfer_no IS '转单号';
COMMENT ON COLUMN finance_supplier_transaction.fee_type IS '费用类型';
COMMENT ON COLUMN finance_supplier_transaction.quantity IS '数量';
COMMENT ON COLUMN finance_supplier_transaction.fee IS '费用';
COMMENT ON COLUMN finance_supplier_transaction.exchange_rate IS '汇率';
COMMENT ON COLUMN finance_supplier_transaction.local_currency_fee IS '本币费用';
COMMENT ON COLUMN finance_supplier_transaction.audit_status IS '审核：1.待审计 2.已审计';
COMMENT ON COLUMN finance_supplier_transaction.write_off_status IS '核销：1.待核销 2.已核销';
COMMENT ON COLUMN finance_supplier_transaction.custom_flag IS '自定义标识';
COMMENT ON COLUMN finance_supplier_transaction.write_off_time IS '核销时间';
COMMENT ON COLUMN finance_supplier_transaction.business_time IS '业务时间';
COMMENT ON COLUMN finance_supplier_transaction.create_by IS '创建者';
COMMENT ON COLUMN finance_supplier_transaction.create_time IS '创建时间';
COMMENT ON COLUMN finance_supplier_transaction.update_by IS '更新者';
COMMENT ON COLUMN finance_supplier_transaction.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_supplier_transaction_update_time
    BEFORE UPDATE
    ON finance_supplier_transaction
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
