CREATE TABLE IF NOT EXISTS finance_sales_cost_transaction
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    transaction_no      text,                                                    -- 流水号
    employee            text,                                                    -- 员工
    waybill_no          text,                                                    -- 运单号
    transfer_no         text,                                                    -- 转单号
    fee_type            text,                                                    -- 费用类型
    fee                 decimal(18,4),                                           -- 费用
    exchange_rate       decimal(10,4),                                           -- 汇率
    local_currency_fee  decimal(18,4),                                           -- 本币费用
    audit_status        smallint,                                                -- 审核：1.待审计 2.已审计
    remark              text,                                                    -- 备注
    business_time       TIMESTAMP WITHOUT TIME ZONE,                             -- 业务时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_sales_cost_transaction IS '销售成本流水表';

COMMENT ON COLUMN finance_sales_cost_transaction.id IS '主键ID';
COMMENT ON COLUMN finance_sales_cost_transaction.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_sales_cost_transaction.transaction_no IS '流水号';
COMMENT ON COLUMN finance_sales_cost_transaction.employee IS '员工';
COMMENT ON COLUMN finance_sales_cost_transaction.waybill_no IS '运单号';
COMMENT ON COLUMN finance_sales_cost_transaction.transfer_no IS '转单号';
COMMENT ON COLUMN finance_sales_cost_transaction.fee_type IS '费用类型';
COMMENT ON COLUMN finance_sales_cost_transaction.fee IS '费用';
COMMENT ON COLUMN finance_sales_cost_transaction.exchange_rate IS '汇率';
COMMENT ON COLUMN finance_sales_cost_transaction.local_currency_fee IS '本币费用';
COMMENT ON COLUMN finance_sales_cost_transaction.audit_status IS '审核：1.待审计 2.已审计';
COMMENT ON COLUMN finance_sales_cost_transaction.remark IS '备注';
COMMENT ON COLUMN finance_sales_cost_transaction.business_time IS '业务时间';
COMMENT ON COLUMN finance_sales_cost_transaction.create_by IS '创建者';
COMMENT ON COLUMN finance_sales_cost_transaction.create_time IS '创建时间';
COMMENT ON COLUMN finance_sales_cost_transaction.update_by IS '更新者';
COMMENT ON COLUMN finance_sales_cost_transaction.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_sales_cost_transaction_update_time
    BEFORE UPDATE
    ON finance_sales_cost_transaction
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
