CREATE TABLE IF NOT EXISTS finance_customer_bill
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    bill_no         text,                                                    -- 账单号
    user_settle     text,                                                    -- 用户（结算方式）
    branch_company  text,                                                    -- 分公司
    currency        text,                                                    -- 币种
    bill_amount     decimal(18,4),                                           -- 账单金额
    paid_amount     decimal(18,4),                                           -- 已支付
    remaining_amount decimal(18,4),                                          -- 余款
    sales_rep       text,                                                    -- 销售代表
    customer_service_rep text,                                               -- 客服代表
    finance_rep     text,                                                    -- 财务代表
    due_action      text,                                                    -- 到期动作
    bill_confirmed  BOOLEAN DEFAULT false,                                   -- 账单确认
    status          smallint,                                                -- 状态：1.待审核 2.待核销 3.已核销
    bill_date       TIMESTAMP WITHOUT TIME ZONE,                             -- 账单日期
    due_date        TIMESTAMP WITHOUT TIME ZONE,                             -- 到期时间
    write_off_time  TIMESTAMP WITHOUT TIME ZONE,                             -- 核销时间
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_customer_bill IS '客户账单表';

COMMENT ON COLUMN finance_customer_bill.id IS '主键ID';
COMMENT ON COLUMN finance_customer_bill.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_customer_bill.bill_no IS '账单号';
COMMENT ON COLUMN finance_customer_bill.user_settle IS '用户（结算方式）';
COMMENT ON COLUMN finance_customer_bill.branch_company IS '分公司';
COMMENT ON COLUMN finance_customer_bill.currency IS '币种';
COMMENT ON COLUMN finance_customer_bill.bill_amount IS '账单金额';
COMMENT ON COLUMN finance_customer_bill.paid_amount IS '已支付';
COMMENT ON COLUMN finance_customer_bill.remaining_amount IS '余款';
COMMENT ON COLUMN finance_customer_bill.sales_rep IS '销售代表';
COMMENT ON COLUMN finance_customer_bill.customer_service_rep IS '客服代表';
COMMENT ON COLUMN finance_customer_bill.finance_rep IS '财务代表';
COMMENT ON COLUMN finance_customer_bill.due_action IS '到期动作';
COMMENT ON COLUMN finance_customer_bill.bill_confirmed IS '账单确认';
COMMENT ON COLUMN finance_customer_bill.status IS '状态：1.待审核 2.待核销 3.已核销';
COMMENT ON COLUMN finance_customer_bill.bill_date IS '账单日期';
COMMENT ON COLUMN finance_customer_bill.due_date IS '到期时间';
COMMENT ON COLUMN finance_customer_bill.write_off_time IS '核销时间';
COMMENT ON COLUMN finance_customer_bill.create_by IS '创建者';
COMMENT ON COLUMN finance_customer_bill.create_time IS '创建时间';
COMMENT ON COLUMN finance_customer_bill.update_by IS '更新者';
COMMENT ON COLUMN finance_customer_bill.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_customer_bill_update_time
    BEFORE UPDATE
    ON finance_customer_bill
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_customer_transaction
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    transaction_no      text,                                                    -- 流水号
    user_name           text,                                                    -- 用户
    user_sales_rep      text,                                                    -- 用户销售代表
    bill_no             text,                                                    -- 账单
    waybill_no          text,                                                    -- 运单号
    bill_of_lading_no   text,                                                    -- 提单号
    transfer_no         text,                                                    -- 转单号
    order_no            text,                                                    -- 单号
    service             text,                                                    -- 服务
    fee_type            text,                                                    -- 费用类型
    quantity            decimal(10,2),                                           -- 数量
    fee                 decimal(18,4),                                           -- 费用
    exchange_rate       decimal(10,4),                                           -- 汇率
    local_currency_fee  decimal(18,4),                                           -- 本币费用
    audit_status        smallint,                                                -- 审核：1.待审计 2.已审计
    write_off_status    smallint,                                                -- 核销：1.待核销 2.已核销
    approval_status     smallint,                                                -- 审批状态
    approver            text,                                                    -- 审批人
    custom_flag         text,                                                    -- 自定义标识
    remark              text,                                                    -- 备注
    write_off_time      TIMESTAMP WITHOUT TIME ZONE,                             -- 核销时间
    business_time       TIMESTAMP WITHOUT TIME ZONE,                             -- 业务时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_customer_transaction IS '客户流水表';

COMMENT ON COLUMN finance_customer_transaction.id IS '主键ID';
COMMENT ON COLUMN finance_customer_transaction.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_customer_transaction.transaction_no IS '流水号';
COMMENT ON COLUMN finance_customer_transaction.user_name IS '用户';
COMMENT ON COLUMN finance_customer_transaction.user_sales_rep IS '用户销售代表';
COMMENT ON COLUMN finance_customer_transaction.bill_no IS '账单';
COMMENT ON COLUMN finance_customer_transaction.waybill_no IS '运单号';
COMMENT ON COLUMN finance_customer_transaction.bill_of_lading_no IS '提单号';
COMMENT ON COLUMN finance_customer_transaction.transfer_no IS '转单号';
COMMENT ON COLUMN finance_customer_transaction.order_no IS '单号';
COMMENT ON COLUMN finance_customer_transaction.service IS '服务';
COMMENT ON COLUMN finance_customer_transaction.fee_type IS '费用类型';
COMMENT ON COLUMN finance_customer_transaction.quantity IS '数量';
COMMENT ON COLUMN finance_customer_transaction.fee IS '费用';
COMMENT ON COLUMN finance_customer_transaction.exchange_rate IS '汇率';
COMMENT ON COLUMN finance_customer_transaction.local_currency_fee IS '本币费用';
COMMENT ON COLUMN finance_customer_transaction.audit_status IS '审核：1.待审计 2.已审计';
COMMENT ON COLUMN finance_customer_transaction.write_off_status IS '核销：1.待核销 2.已核销';
COMMENT ON COLUMN finance_customer_transaction.approval_status IS '审批状态';
COMMENT ON COLUMN finance_customer_transaction.approver IS '审批人';
COMMENT ON COLUMN finance_customer_transaction.custom_flag IS '自定义标识';
COMMENT ON COLUMN finance_customer_transaction.remark IS '备注';
COMMENT ON COLUMN finance_customer_transaction.write_off_time IS '核销时间';
COMMENT ON COLUMN finance_customer_transaction.business_time IS '业务时间';
COMMENT ON COLUMN finance_customer_transaction.create_by IS '创建者';
COMMENT ON COLUMN finance_customer_transaction.create_time IS '创建时间';
COMMENT ON COLUMN finance_customer_transaction.update_by IS '更新者';
COMMENT ON COLUMN finance_customer_transaction.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_customer_transaction_update_time
    BEFORE UPDATE
    ON finance_customer_transaction
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_price_maintenance
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    name            text,                                                    -- 名称
    service         text,                                                    -- 服务
    receive_area    text,                                                    -- 收货区域
    priority        integer,                                                 -- 优先级
    user_level      text,                                                    -- 用户等级
    user_name       text,                                                    -- 用户
    min_weight      decimal(10,2),                                           -- 最小重量
    max_weight      decimal(10,2),                                           -- 最大重量
    zip_prefix      text,                                                    -- 邮编开头
    parent_id       bigint,                                                  -- 父级
    status          BOOLEAN DEFAULT true,                                    -- 状态
    price_type      smallint,                                                -- 价格类型：1.公布价 2.销售员底价 3.成本价
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_price_maintenance IS '运价维护表';

COMMENT ON COLUMN finance_price_maintenance.id IS '主键ID';
COMMENT ON COLUMN finance_price_maintenance.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_price_maintenance.name IS '名称';
COMMENT ON COLUMN finance_price_maintenance.service IS '服务';
COMMENT ON COLUMN finance_price_maintenance.receive_area IS '收货区域';
COMMENT ON COLUMN finance_price_maintenance.priority IS '优先级';
COMMENT ON COLUMN finance_price_maintenance.user_level IS '用户等级';
COMMENT ON COLUMN finance_price_maintenance.user_name IS '用户';
COMMENT ON COLUMN finance_price_maintenance.min_weight IS '最小重量';
COMMENT ON COLUMN finance_price_maintenance.max_weight IS '最大重量';
COMMENT ON COLUMN finance_price_maintenance.zip_prefix IS '邮编开头';
COMMENT ON COLUMN finance_price_maintenance.parent_id IS '父级';
COMMENT ON COLUMN finance_price_maintenance.status IS '状态';
COMMENT ON COLUMN finance_price_maintenance.price_type IS '价格类型：1.公布价 2.销售员底价 3.成本价';
COMMENT ON COLUMN finance_price_maintenance.create_by IS '创建者';
COMMENT ON COLUMN finance_price_maintenance.create_time IS '创建时间';
COMMENT ON COLUMN finance_price_maintenance.update_by IS '更新者';
COMMENT ON COLUMN finance_price_maintenance.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_price_maintenance_update_time
    BEFORE UPDATE
    ON finance_price_maintenance
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_payable_report
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    user_name       text,                                                    -- 用户
    currency        text,                                                    -- 币种
    turnover        decimal(18,4),                                           -- 营业额
    paid_amount     decimal(18,4),                                           -- 已支付
    pending_amount  decimal(18,4),                                           -- 待支付
    issued_bill     decimal(18,4),                                           -- 已出账单
    pending_bill    decimal(18,4),                                           -- 待出账单
    paid_bill       decimal(18,4),                                           -- 已付账单
    pending_payment_bill decimal(18,4),                                     -- 待付账单
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_payable_report IS '应付报表表';

COMMENT ON COLUMN finance_payable_report.id IS '主键ID';
COMMENT ON COLUMN finance_payable_report.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_payable_report.user_name IS '用户';
COMMENT ON COLUMN finance_payable_report.currency IS '币种';
COMMENT ON COLUMN finance_payable_report.turnover IS '营业额';
COMMENT ON COLUMN finance_payable_report.paid_amount IS '已支付';
COMMENT ON COLUMN finance_payable_report.pending_amount IS '待支付';
COMMENT ON COLUMN finance_payable_report.issued_bill IS '已出账单';
COMMENT ON COLUMN finance_payable_report.pending_bill IS '待出账单';
COMMENT ON COLUMN finance_payable_report.paid_bill IS '已付账单';
COMMENT ON COLUMN finance_payable_report.pending_payment_bill IS '待付账单';
COMMENT ON COLUMN finance_payable_report.create_by IS '创建者';
COMMENT ON COLUMN finance_payable_report.create_time IS '创建时间';
COMMENT ON COLUMN finance_payable_report.update_by IS '更新者';
COMMENT ON COLUMN finance_payable_report.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_payable_report_update_time
    BEFORE UPDATE
    ON finance_payable_report
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_receivable_report
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    user_name       text,                                                    -- 用户
    currency        text,                                                    -- 币种
    turnover        decimal(18,4),                                           -- 营业额
    paid_amount     decimal(18,4),                                           -- 已支付
    pending_amount  decimal(18,4),                                           -- 待支付
    issued_bill     decimal(18,4),                                           -- 已出账单
    pending_bill    decimal(18,4),                                           -- 待出账单
    paid_bill       decimal(18,4),                                           -- 已付账单
    pending_payment_bill decimal(18,4),                                     -- 待付账单
    actual_amount   decimal(18,4),                                           -- 账户实际金额
    customer_service_rep text,                                               -- 客服代表
    sales_rep       text,                                                    -- 销售代表
    finance_rep     text,                                                    -- 财务代表
    settlement_method text,                                                  -- 结算方式
    user_level      text,                                                    -- 用户等级
    user_remark     text,                                                    -- 用户备注
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_receivable_report IS '应收报表表';

COMMENT ON COLUMN finance_receivable_report.id IS '主键ID';
COMMENT ON COLUMN finance_receivable_report.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_receivable_report.user_name IS '用户';
COMMENT ON COLUMN finance_receivable_report.currency IS '币种';
COMMENT ON COLUMN finance_receivable_report.turnover IS '营业额';
COMMENT ON COLUMN finance_receivable_report.paid_amount IS '已支付';
COMMENT ON COLUMN finance_receivable_report.pending_amount IS '待支付';
COMMENT ON COLUMN finance_receivable_report.issued_bill IS '已出账单';
COMMENT ON COLUMN finance_receivable_report.pending_bill IS '待出账单';
COMMENT ON COLUMN finance_receivable_report.paid_bill IS '已付账单';
COMMENT ON COLUMN finance_receivable_report.pending_payment_bill IS '待付账单';
COMMENT ON COLUMN finance_receivable_report.actual_amount IS '账户实际金额';
COMMENT ON COLUMN finance_receivable_report.customer_service_rep IS '客服代表';
COMMENT ON COLUMN finance_receivable_report.sales_rep IS '销售代表';
COMMENT ON COLUMN finance_receivable_report.finance_rep IS '财务代表';
COMMENT ON COLUMN finance_receivable_report.settlement_method IS '结算方式';
COMMENT ON COLUMN finance_receivable_report.user_level IS '用户等级';
COMMENT ON COLUMN finance_receivable_report.user_remark IS '用户备注';
COMMENT ON COLUMN finance_receivable_report.create_by IS '创建者';
COMMENT ON COLUMN finance_receivable_report.create_time IS '创建时间';
COMMENT ON COLUMN finance_receivable_report.update_by IS '更新者';
COMMENT ON COLUMN finance_receivable_report.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_receivable_report_update_time
    BEFORE UPDATE
    ON finance_receivable_report
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_waybill_audit
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    waybill_no          text,                                                    -- 运单号
    user_name           text,                                                    -- 用户
    service             text,                                                    -- 服务
    country             text,                                                    -- 国家
    piece_count         integer,                                                 -- 件数
    actual_weight       decimal(10,2),                                           -- 实重
    volume_weight       decimal(10,2),                                           -- 材重
    charge_weight       decimal(10,2),                                           -- 收费重
    supplier_weight     decimal(10,2),                                           -- 供应商重量
    status              smallint,                                                -- 状态：1已收货 2转运中 3已签收 4退件
    receivable_amount   decimal(18,4),                                           -- 应收
    payable_amount      decimal(18,4),                                           -- 应付
    sales_cost          decimal(18,4),                                           -- 销售成本
    sales_commission    decimal(18,4),                                           -- 销售提成
    gross_profit        decimal(18,4),                                           -- 毛利
    customer_service_rep text,                                                   -- 客服代表
    sales_rep           text,                                                    -- 销售代表
    picking_time        TIMESTAMP WITHOUT TIME ZONE,                             -- 拣货时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_waybill_audit IS '运单审计表';

COMMENT ON COLUMN finance_waybill_audit.id IS '主键ID';
COMMENT ON COLUMN finance_waybill_audit.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_waybill_audit.waybill_no IS '运单号';
COMMENT ON COLUMN finance_waybill_audit.user_name IS '用户';
COMMENT ON COLUMN finance_waybill_audit.service IS '服务';
COMMENT ON COLUMN finance_waybill_audit.country IS '国家';
COMMENT ON COLUMN finance_waybill_audit.piece_count IS '件数';
COMMENT ON COLUMN finance_waybill_audit.actual_weight IS '实重';
COMMENT ON COLUMN finance_waybill_audit.volume_weight IS '材重';
COMMENT ON COLUMN finance_waybill_audit.charge_weight IS '收费重';
COMMENT ON COLUMN finance_waybill_audit.supplier_weight IS '供应商重量';
COMMENT ON COLUMN finance_waybill_audit.status IS '状态：1已收货 2转运中 3已签收 4退件';
COMMENT ON COLUMN finance_waybill_audit.receivable_amount IS '应收';
COMMENT ON COLUMN finance_waybill_audit.payable_amount IS '应付';
COMMENT ON COLUMN finance_waybill_audit.sales_cost IS '销售成本';
COMMENT ON COLUMN finance_waybill_audit.sales_commission IS '销售提成';
COMMENT ON COLUMN finance_waybill_audit.gross_profit IS '毛利';
COMMENT ON COLUMN finance_waybill_audit.customer_service_rep IS '客服代表';
COMMENT ON COLUMN finance_waybill_audit.sales_rep IS '销售代表';
COMMENT ON COLUMN finance_waybill_audit.picking_time IS '拣货时间';
COMMENT ON COLUMN finance_waybill_audit.create_by IS '创建者';
COMMENT ON COLUMN finance_waybill_audit.create_time IS '创建时间';
COMMENT ON COLUMN finance_waybill_audit.update_by IS '更新者';
COMMENT ON COLUMN finance_waybill_audit.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_waybill_audit_update_time
    BEFORE UPDATE
    ON finance_waybill_audit
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_transaction
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    transaction_no      text,                                                    -- 流水号
    user_name           text,                                                    -- 用户
    company_account     text,                                                    -- 公司账户
    user_account        text,                                                    -- 用户账户
    currency            text,                                                    -- 币种
    amount              decimal(18,4),                                           -- 金额
    fee                 decimal(18,4),                                           -- 手续费
    type                smallint,                                                -- 类型：1客户充值 2客户提现 3支付供应商 4供应商退款 5经营收入 6经营支出 7工资发放 8提成发放 9内部转账
    audit_transaction_no text,                                                   -- 审核流水号
    payment_status      smallint,                                                -- 支付状态
    invoiced            BOOLEAN DEFAULT false,                                   -- 是否已开票
    bill_no             text,                                                    -- 账单
    audit_time          TIMESTAMP WITHOUT TIME ZONE,                             -- 审核时间
    payment_time        TIMESTAMP WITHOUT TIME ZONE,                             -- 支付时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_transaction IS '财务流水表';

COMMENT ON COLUMN finance_transaction.id IS '主键ID';
COMMENT ON COLUMN finance_transaction.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_transaction.transaction_no IS '流水号';
COMMENT ON COLUMN finance_transaction.user_name IS '用户';
COMMENT ON COLUMN finance_transaction.company_account IS '公司账户';
COMMENT ON COLUMN finance_transaction.user_account IS '用户账户';
COMMENT ON COLUMN finance_transaction.currency IS '币种';
COMMENT ON COLUMN finance_transaction.amount IS '金额';
COMMENT ON COLUMN finance_transaction.fee IS '手续费';
COMMENT ON COLUMN finance_transaction.type IS '类型：1客户充值 2客户提现 3支付供应商 4供应商退款 5经营收入 6经营支出 7工资发放 8提成发放 9内部转账';
COMMENT ON COLUMN finance_transaction.audit_transaction_no IS '审核流水号';
COMMENT ON COLUMN finance_transaction.payment_status IS '支付状态';
COMMENT ON COLUMN finance_transaction.invoiced IS '是否已开票';
COMMENT ON COLUMN finance_transaction.bill_no IS '账单';
COMMENT ON COLUMN finance_transaction.audit_time IS '审核时间';
COMMENT ON COLUMN finance_transaction.payment_time IS '支付时间';
COMMENT ON COLUMN finance_transaction.create_by IS '创建者';
COMMENT ON COLUMN finance_transaction.create_time IS '创建时间';
COMMENT ON COLUMN finance_transaction.update_by IS '更新者';
COMMENT ON COLUMN finance_transaction.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_transaction_update_time
    BEFORE UPDATE
    ON finance_transaction
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
