CREATE TABLE IF NOT EXISTS finance_monthly_statement
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    start_time      TIMESTAMP WITHOUT TIME ZONE,                            -- 开始时间
    end_time        TIMESTAMP WITHOUT TIME ZONE,                            -- 结束时间
    receivable      BOOLEAN,                                                -- 应收（锁定/开启）
    payable         BOOLEAN,                                                -- 应付（锁定/开启）
    sales_cost      BOOLEAN,                                                -- 销售成本（锁定/开启）
    waybill         BOOLEAN,                                                -- 运单（锁定/开启）
    bill_of_lading  BOOLEAN,                                                -- 提单（锁定/开启）
    remark          text,                                                   -- 备注
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_monthly_statement IS '月结单';

COMMENT ON COLUMN finance_monthly_statement.id IS '主键ID';
COMMENT ON COLUMN finance_monthly_statement.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_monthly_statement.start_time IS '开始时间';
COMMENT ON COLUMN finance_monthly_statement.end_time IS '结束时间';
COMMENT ON COLUMN finance_monthly_statement.receivable IS '应收';
COMMENT ON COLUMN finance_monthly_statement.payable IS '应付';
COMMENT ON COLUMN finance_monthly_statement.sales_cost IS '销售成本';
COMMENT ON COLUMN finance_monthly_statement.waybill IS '运单';
COMMENT ON COLUMN finance_monthly_statement.bill_of_lading IS '提单';
COMMENT ON COLUMN finance_monthly_statement.remark IS '备注';
COMMENT ON COLUMN finance_monthly_statement.create_by IS '创建者';
COMMENT ON COLUMN finance_monthly_statement.create_time IS '创建时间';
COMMENT ON COLUMN finance_monthly_statement.update_by IS '更新者';
COMMENT ON COLUMN finance_monthly_statement.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_monthly_statement_update_time
    BEFORE UPDATE
    ON finance_monthly_statement
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();