CREATE TABLE IF NOT EXISTS finance_account
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    account_name    text not null,                                          -- 账户名称
    currency        text,                                                    -- 币种
    balance         decimal(18,4) DEFAULT 0,                                 -- 余额
    bank_name       text,                                                    -- 开户行
    type            smallint not null,                                       -- 类型：1.公司 2.客户 3.供应商 4.员工
    visible         BOOLEAN DEFAULT true,                                    -- 用户可见
    remark          text,                                                   -- 备注
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE finance_account IS '账户表';
COMMENT ON COLUMN finance_account.id IS '主键ID';
COMMENT ON COLUMN finance_account.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_account.account_name IS '账户名称';
COMMENT ON COLUMN finance_account.currency IS '币种';
COMMENT ON COLUMN finance_account.balance IS '余额';
COMMENT ON COLUMN finance_account.bank_name IS '开户行';
COMMENT ON COLUMN finance_account.type IS '类型：1.公司 2.客户 3.供应商 4.员工';
COMMENT ON COLUMN finance_account.visible IS '用户可见';
COMMENT ON COLUMN finance_account.remark IS '备注';
COMMENT ON COLUMN finance_account.create_by IS '创建者';
COMMENT ON COLUMN finance_account.create_time IS '创建时间';
COMMENT ON COLUMN finance_account.update_by IS '更新者';
COMMENT ON COLUMN finance_account.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_account_update_time
    BEFORE UPDATE
    ON finance_account
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS finance_account_transaction
(
    id                  bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id           uuid not null,                                           -- 租户ID
    transaction_no      text,                                                    -- 流水号
    account_id          bigint,                                                  -- 账户ID
    customer_id         bigint,                                                  -- 客户ID
    transaction_type    smallint,                                                -- 类型：1.公司 2.客户 3.供应商 4.员工
    currency            text,                                                    -- 币种
    amount              decimal(18,4),                                           -- 金额
    fee                 decimal(18,4),                                           -- 手续费
    credit_amount       decimal(18,4),                                           -- 入账金额
    remark              text,                                                    -- 备注
    payment_time        TIMESTAMP WITHOUT TIME ZONE,                             -- 支付时间
    create_by           text DEFAULT 'admin',                                    -- 创建者
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,   -- 创建时间
    update_by           text DEFAULT 'admin',                                    -- 更新者
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    -- 更新时间
);

COMMENT ON TABLE finance_account_transaction IS '账户流水表';

COMMENT ON COLUMN finance_account_transaction.id IS '主键ID';
COMMENT ON COLUMN finance_account_transaction.tenant_id IS '租户ID';
COMMENT ON COLUMN finance_account_transaction.transaction_no IS '流水号';
COMMENT ON COLUMN finance_account_transaction.account_id IS '账户ID';
COMMENT ON COLUMN finance_account_transaction.customer_id IS '客户ID';
COMMENT ON COLUMN finance_account_transaction.transaction_type IS '类型：1.公司 2.客户 3.供应商 4.员工';
COMMENT ON COLUMN finance_account_transaction.currency IS '币种';
COMMENT ON COLUMN finance_account_transaction.amount IS '金额';
COMMENT ON COLUMN finance_account_transaction.fee IS '手续费';
COMMENT ON COLUMN finance_account_transaction.credit_amount IS '入账金额';
COMMENT ON COLUMN finance_account_transaction.remark IS '备注';
COMMENT ON COLUMN finance_account_transaction.payment_time IS '支付时间';
COMMENT ON COLUMN finance_account_transaction.create_by IS '创建者';
COMMENT ON COLUMN finance_account_transaction.create_time IS '创建时间';
COMMENT ON COLUMN finance_account_transaction.update_by IS '更新者';
COMMENT ON COLUMN finance_account_transaction.update_time IS '更新时间';

CREATE TRIGGER trigger_finance_account_transaction_update_time
    BEFORE UPDATE
    ON finance_account_transaction
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
