CREATE TABLE finance_approval
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            uuid        NOT NULL,
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL,
    created_by           TEXT        NOT NULL,
    updated_by           TEXT        NOT NULL,
    approval_id          BIGINT,           -- 审批编号
    type                 TEXT,             -- 类型
    associate_order_id   TEXT,             -- 关联单号
    associate_order_user TEXT,             -- 关联单号用户
    reason               TEXT,             -- 事由
    fee_type             TEXT,             -- 费用类型
    fee_amount           DOUBLE PRECISION, -- 费用金额
    modifier             DOUBLE PRECISION, -- 加减值/延迟天数
    bubble_modifier      DOUBLE PRECISION, -- 计泡系数
    approver             TEXT,             -- 审批人
    applicant            TEXT,             -- 申请人
    approval_status      TEXT,             -- 审批状态
    approval_reason      TEXT,             -- 审批理由
    pay_status           TEXT,             -- 支付状态
    happened_at          timestamptz       -- 发生时间
);