BEGIN;

CREATE TABLE finance_approval
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     uuid        NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL,
    created_by    TEXT        NOT NULL,
    updated_by    TEXT        NOT NULL,
    creator_id    uuid        NOT NULL REFERENCES users (id),
    -- 审批类型，根据 type 去对应的表单表查询申请内容
    approval_type TEXT        NOT NULL CHECK ( approval_type = '付款' OR approval_type = '账单延期' OR approval_type = '运单优惠' ),
    reason        TEXT        NOT NULL,
    remark        TEXT,
    -- 抄送人的 user_id 列表
    cc_user_ids   uuid[],
    -- 附件链接列表
    file_urls     TEXT[]
);
COMMENT ON TABLE finance_approval IS '财务-审批';
CREATE INDEX ON finance_approval USING gin (cc_user_ids);



CREATE TABLE finance_approval_approvers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid        NOT NULL,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    created_by  TEXT        NOT NULL,
    updated_by  TEXT        NOT NULL,
    approval_id BIGINT      NOT NULL REFERENCES finance_approval (id),
    user_id     uuid        NOT NULL REFERENCES users (id),
    -- 该审批人对该申请的状态
    status      TEXT        NOT NULL CHECK ( status IN ('审批中', '已批准', '已拒绝') )
);
COMMENT ON TABLE finance_approval_approvers IS '审批人与审批状态';
CREATE INDEX ON finance_approval_approvers (user_id, status);



CREATE TABLE finance_approval_type_payments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     uuid           NOT NULL,
    created_at    timestamptz    NOT NULL,
    updated_at    timestamptz    NOT NULL,
    created_by    TEXT           NOT NULL,
    updated_by    TEXT           NOT NULL,
    approval_id   BIGINT         NOT NULL REFERENCES finance_approval (id),
    fee_type_code TEXT           NOT NULL REFERENCES finance_fee_type (code),
    amount        NUMERIC(18, 8) NOT NULL,
    currency_code TEXT           NOT NULL REFERENCES finance_currency (code),
    happened_at   timestamptz    NOT NULL
);
COMMENT ON TABLE finance_approval_type_payments IS '审批类型-付款';



CREATE TABLE finance_approval_type_billing_periods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   uuid        NOT NULL,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    created_by  TEXT        NOT NULL,
    updated_by  TEXT        NOT NULL,
    approval_id BIGINT      NOT NULL REFERENCES finance_approval (id),
    -- todo: 账单号
    bill_id     TEXT,
    days        INTEGER     NOT NULL
);
COMMENT ON TABLE finance_approval_type_billing_periods IS '审批类型-账单延期';



CREATE TABLE finance_approval_type_waybill_discounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     uuid        NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL,
    created_by    TEXT        NOT NULL,
    updated_by    TEXT        NOT NULL,
    approval_id   BIGINT      NOT NULL REFERENCES finance_approval (id),
    -- todo: 运单号
    waybill_id    TEXT,
    fee_type_code TEXT        NOT NULL REFERENCES finance_fee_type (code),
    discount_type TEXT        NOT NULL CHECK ( discount_type IN ('价格优惠', '重量优惠') ),
    form          jsonb       NOT NULL
);
COMMENT ON TABLE finance_approval_type_waybill_discounts IS '审批类型-运单优惠';

COMMIT;