-- 货币
CREATE TABLE finance_currency
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  uuid        NOT NULL,
    created_at timestamptz NOT NULL,
    created_by TEXT        NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by TEXT        NOT NULL,
    code       TEXT        NOT NULL UNIQUE,
    name       TEXT        NOT NULL
);
CREATE INDEX ON finance_currency (code);
COMMENT ON TABLE finance_currency IS '货币';

CREATE TABLE finance_currency_exchange
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            uuid           NOT NULL,
    created_at           timestamptz    NOT NULL,
    created_by           TEXT           NOT NULL,
    updated_at           timestamptz    NOT NULL,
    updated_by           TEXT           NOT NULL,
    code                 TEXT           NOT NULL REFERENCES finance_currency (code),
    application_scenario TEXT           NOT NULL CHECK ( application_scenario = '应收' OR application_scenario = '应付'),
    rate                 NUMERIC(18, 8) NOT NULL,
    effective_from       timestamptz    NOT NULL
);
-- 确保生效时间唯一
CREATE UNIQUE INDEX ON finance_currency_exchange (code, application_scenario, effective_from);
COMMENT ON TABLE finance_currency_exchange IS '货币的汇率记录';
COMMENT ON COLUMN finance_currency_exchange.application_scenario IS '应用场景：应收/应付';
COMMENT ON COLUMN finance_currency_exchange.effective_from IS '生效开始时间';