CREATE TABLE IF NOT EXISTS order_waybill
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_no      text,                                                    -- 运单号
    type            smallint,                                                -- 类型：1已下单 2已收货 3转运中 4已签收 5退件 6已取消
    user_name       text,                                                    -- 用户
    service         text,                                                    -- 服务
    receiver        text,                                                    -- 收件人
    country         text,                                                    -- 国家
    piece_count     integer,                                                 -- 件数
    bubble_ratio    decimal(10,2),                                           -- 泡比
    customer_weight decimal(10,2),                                           -- 客户重量
    customer_volume decimal(10,2),                                           -- 客户体积
    declare_value   decimal(18,4),                                           -- 申报价值
    actual_weight   decimal(10,2),                                           -- 实重
    volume_weight   decimal(10,2),                                           -- 材重
    volume          decimal(10,2),                                           -- 体积
    charge_weight   decimal(10,2),                                           -- 收费重
    customs_method  text,                                                    -- 报关方式
    tax_method      text,                                                    -- 交税方式
    carrier         text,                                                    -- 承运
    main_product    text,                                                    -- 主品名
    product_attr    text,                                                    -- 物品属性
    remark          text,                                                    -- 备注
    freight_station text,                                                    -- 货站
    order_time      TIMESTAMP WITHOUT TIME ZONE,                             -- 下单时间
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_waybill IS '运单表';

COMMENT ON COLUMN order_waybill.id IS '主键ID';
COMMENT ON COLUMN order_waybill.tenant_id IS '租户ID';
COMMENT ON COLUMN order_waybill.waybill_no IS '运单号';
COMMENT ON COLUMN order_waybill.type IS '类型：1已下单 2已收货 3转运中 4已签收 5退件 6已取消';
COMMENT ON COLUMN order_waybill.user_name IS '用户';
COMMENT ON COLUMN order_waybill.service IS '服务';
COMMENT ON COLUMN order_waybill.receiver IS '收件人';
COMMENT ON COLUMN order_waybill.country IS '国家';
COMMENT ON COLUMN order_waybill.piece_count IS '件数';
COMMENT ON COLUMN order_waybill.bubble_ratio IS '泡比';
COMMENT ON COLUMN order_waybill.customer_weight IS '客户重量';
COMMENT ON COLUMN order_waybill.customer_volume IS '客户体积';
COMMENT ON COLUMN order_waybill.declare_value IS '申报价值';
COMMENT ON COLUMN order_waybill.actual_weight IS '实重';
COMMENT ON COLUMN order_waybill.volume_weight IS '材重';
COMMENT ON COLUMN order_waybill.volume IS '体积';
COMMENT ON COLUMN order_waybill.charge_weight IS '收费重';
COMMENT ON COLUMN order_waybill.customs_method IS '报关方式';
COMMENT ON COLUMN order_waybill.tax_method IS '交税方式';
COMMENT ON COLUMN order_waybill.carrier IS '承运';
COMMENT ON COLUMN order_waybill.main_product IS '主品名';
COMMENT ON COLUMN order_waybill.product_attr IS '物品属性';
COMMENT ON COLUMN order_waybill.remark IS '备注';
COMMENT ON COLUMN order_waybill.freight_station IS '货站';
COMMENT ON COLUMN order_waybill.order_time IS '下单时间';
COMMENT ON COLUMN order_waybill.create_by IS '创建者';
COMMENT ON COLUMN order_waybill.create_time IS '创建时间';
COMMENT ON COLUMN order_waybill.update_by IS '更新者';
COMMENT ON COLUMN order_waybill.update_time IS '更新时间';

CREATE TRIGGER trigger_order_waybill_update_time
    BEFORE UPDATE
    ON order_waybill
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_route
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    operation_time  TIMESTAMP WITHOUT TIME ZONE,                             -- 操作时间
    operation_info  text,                                                    -- 操作信息
    remark          text,                                                    -- 备注
    common_address  text,                                                    -- 常用地址
    city            text,                                                    -- 城市
    province        text,                                                    -- 省份
    zip_code        text,                                                    -- 邮编
    country         text,                                                    -- 国家
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_route IS '运单路由信息表';

COMMENT ON COLUMN order_route.id IS '主键ID';
COMMENT ON COLUMN order_route.tenant_id IS '租户ID';
COMMENT ON COLUMN order_route.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_route.operation_time IS '操作时间';
COMMENT ON COLUMN order_route.operation_info IS '操作信息';
COMMENT ON COLUMN order_route.remark IS '备注';
COMMENT ON COLUMN order_route.common_address IS '常用地址';
COMMENT ON COLUMN order_route.city IS '城市';
COMMENT ON COLUMN order_route.province IS '省份';
COMMENT ON COLUMN order_route.zip_code IS '邮编';
COMMENT ON COLUMN order_route.country IS '国家';
COMMENT ON COLUMN order_route.create_by IS '创建者';
COMMENT ON COLUMN order_route.create_time IS '创建时间';
COMMENT ON COLUMN order_route.update_by IS '更新者';
COMMENT ON COLUMN order_route.update_time IS '更新时间';

CREATE TRIGGER trigger_order_route_update_time
    BEFORE UPDATE
    ON order_route
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_container
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    container_no    text,                                                    -- 箱号
    reference_no    text,                                                    -- 参考号
    customer_data   text,                                                    -- 客户数据
    picking_data    text,                                                    -- 拣货数据(实重/材重)
    perimeter       decimal(10,2),                                           -- 围长
    bill_of_lading_no text,                                                  -- 提单号
    carrier         text,                                                    -- 承运商
    express_mark    BOOLEAN DEFAULT false,                                   -- 快递标
    fba_mark        BOOLEAN DEFAULT false,                                   -- FBA标
    abnormal_flag   BOOLEAN DEFAULT false,                                   -- 异常标识
    label_change    BOOLEAN DEFAULT false,                                   -- 换标
    check_status    BOOLEAN DEFAULT false,                                   -- 核对
    check_goods     BOOLEAN DEFAULT false,                                   -- 查货
    intercept       BOOLEAN DEFAULT false,                                   -- 拦截
    freight_station text,                                                    -- 货站
    status          smallint,                                                -- 状态：1已下单 2未下单
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_container IS '运单货箱信息表';

COMMENT ON COLUMN order_container.id IS '主键ID';
COMMENT ON COLUMN order_container.tenant_id IS '租户ID';
COMMENT ON COLUMN order_container.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_container.container_no IS '箱号';
COMMENT ON COLUMN order_container.reference_no IS '参考号';
COMMENT ON COLUMN order_container.customer_data IS '客户数据';
COMMENT ON COLUMN order_container.picking_data IS '拣货数据(实重/材重)';
COMMENT ON COLUMN order_container.perimeter IS '围长';
COMMENT ON COLUMN order_container.bill_of_lading_no IS '提单号';
COMMENT ON COLUMN order_container.carrier IS '承运商';
COMMENT ON COLUMN order_container.express_mark IS '快递标';
COMMENT ON COLUMN order_container.fba_mark IS 'FBA标';
COMMENT ON COLUMN order_container.abnormal_flag IS '异常标识';
COMMENT ON COLUMN order_container.label_change IS '换标';
COMMENT ON COLUMN order_container.check_status IS '核对';
COMMENT ON COLUMN order_container.check_goods IS '查货';
COMMENT ON COLUMN order_container.intercept IS '拦截';
COMMENT ON COLUMN order_container.freight_station IS '货站';
COMMENT ON COLUMN order_container.status IS '状态：1已下单 2未下单';
COMMENT ON COLUMN order_container.create_by IS '创建者';
COMMENT ON COLUMN order_container.create_time IS '创建时间';
COMMENT ON COLUMN order_container.update_by IS '更新者';
COMMENT ON COLUMN order_container.update_time IS '更新时间';

CREATE TRIGGER trigger_order_container_update_time
    BEFORE UPDATE
    ON order_container
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_declaration
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    sku             text,                                                    -- 商品SKU
    chinese_name    text,                                                    -- 中文品名
    english_name    text,                                                    -- 英文品名
    declare_price   decimal(18,4),                                           -- 申报单价
    quantity        integer,                                                 -- 数量
    material        text,                                                    -- 材质
    purpose         text,                                                    -- 用途
    model           text,                                                    -- 型号
    product_weight  decimal(10,2),                                           -- 产品重量
    image_url       text,                                                    -- 图片链接
    customs_code    text,                                                    -- 海关编码
    image           text,                                                    -- 图片
    is_electric     BOOLEAN DEFAULT false,                                   -- 产品带电
    is_magnetic     BOOLEAN DEFAULT false,                                   -- 产品带磁
    product_image   text,                                                    -- 产品图片
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_declaration IS '运单申报信息表';

COMMENT ON COLUMN order_declaration.id IS '主键ID';
COMMENT ON COLUMN order_declaration.tenant_id IS '租户ID';
COMMENT ON COLUMN order_declaration.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_declaration.sku IS '商品SKU';
COMMENT ON COLUMN order_declaration.chinese_name IS '中文品名';
COMMENT ON COLUMN order_declaration.english_name IS '英文品名';
COMMENT ON COLUMN order_declaration.declare_price IS '申报单价';
COMMENT ON COLUMN order_declaration.quantity IS '数量';
COMMENT ON COLUMN order_declaration.material IS '材质';
COMMENT ON COLUMN order_declaration.purpose IS '用途';
COMMENT ON COLUMN order_declaration.model IS '型号';
COMMENT ON COLUMN order_declaration.product_weight IS '产品重量';
COMMENT ON COLUMN order_declaration.image_url IS '图片链接';
COMMENT ON COLUMN order_declaration.customs_code IS '海关编码';
COMMENT ON COLUMN order_declaration.image IS '图片';
COMMENT ON COLUMN order_declaration.is_electric IS '产品带电';
COMMENT ON COLUMN order_declaration.is_magnetic IS '产品带磁';
COMMENT ON COLUMN order_declaration.product_image IS '产品图片';
COMMENT ON COLUMN order_declaration.create_by IS '创建者';
COMMENT ON COLUMN order_declaration.create_time IS '创建时间';
COMMENT ON COLUMN order_declaration.update_by IS '更新者';
COMMENT ON COLUMN order_declaration.update_time IS '更新时间';

CREATE TRIGGER trigger_order_declaration_update_time
    BEFORE UPDATE
    ON order_declaration
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_attachment
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    attachment_type text,                                                    -- 附件类型
    attachment_url  text,                                                    -- 附件url
    user_visible    BOOLEAN DEFAULT true,                                    -- 用户可见
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_attachment IS '运单附件表';

COMMENT ON COLUMN order_attachment.id IS '主键ID';
COMMENT ON COLUMN order_attachment.tenant_id IS '租户ID';
COMMENT ON COLUMN order_attachment.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_attachment.attachment_type IS '附件类型';
COMMENT ON COLUMN order_attachment.attachment_url IS '附件url';
COMMENT ON COLUMN order_attachment.user_visible IS '用户可见';
COMMENT ON COLUMN order_attachment.create_by IS '创建者';
COMMENT ON COLUMN order_attachment.create_time IS '创建时间';
COMMENT ON COLUMN order_attachment.update_by IS '更新者';
COMMENT ON COLUMN order_attachment.update_time IS '更新时间';

CREATE TRIGGER trigger_order_attachment_update_time
    BEFORE UPDATE
    ON order_attachment
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_delivery
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    carrier_account text,                                                    -- 承运账号
    unique_ref_no   text,                                                    -- 唯一参考号
    warehouse_code  text,                                                    -- 仓库代码
    receiver        text,                                                    -- 收件人
    address1        text,                                                    -- 地址一
    address2        text,                                                    -- 地址二
    address3        text,                                                    -- 地址三
    city            text,                                                    -- 城市
    state           text,                                                    -- 省/州
    zip_code        text,                                                    -- 邮编
    country         text,                                                    -- 国家
    phone           text,                                                    -- 电话
    email           text,                                                    -- 邮箱
    boxes           text,                                                    -- 箱子
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_delivery IS '运单派送表';

COMMENT ON COLUMN order_delivery.id IS '主键ID';
COMMENT ON COLUMN order_delivery.tenant_id IS '租户ID';
COMMENT ON COLUMN order_delivery.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_delivery.carrier_account IS '承运账号';
COMMENT ON COLUMN order_delivery.unique_ref_no IS '唯一参考号';
COMMENT ON COLUMN order_delivery.warehouse_code IS '仓库代码';
COMMENT ON COLUMN order_delivery.receiver IS '收件人';
COMMENT ON COLUMN order_delivery.address1 IS '地址一';
COMMENT ON COLUMN order_delivery.address2 IS '地址二';
COMMENT ON COLUMN order_delivery.address3 IS '地址三';
COMMENT ON COLUMN order_delivery.city IS '城市';
COMMENT ON COLUMN order_delivery.state IS '省/州';
COMMENT ON COLUMN order_delivery.zip_code IS '邮编';
COMMENT ON COLUMN order_delivery.country IS '国家';
COMMENT ON COLUMN order_delivery.phone IS '电话';
COMMENT ON COLUMN order_delivery.email IS '邮箱';
COMMENT ON COLUMN order_delivery.boxes IS '箱子';
COMMENT ON COLUMN order_delivery.create_by IS '创建者';
COMMENT ON COLUMN order_delivery.create_time IS '创建时间';
COMMENT ON COLUMN order_delivery.update_by IS '更新者';
COMMENT ON COLUMN order_delivery.update_time IS '更新时间';

CREATE TRIGGER trigger_order_delivery_update_time
    BEFORE UPDATE
    ON order_delivery
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_work_order
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    title           text,                                                    -- 标题
    related_no      text,                                                    -- 关联单号
    description     text,                                                    -- 描述
    followers       text,                                                    -- 关注者
    responsible     text,                                                    -- 负责人
    remind_time     TIMESTAMP WITHOUT TIME ZONE,                             -- 提醒时间
    user_visible    BOOLEAN DEFAULT true,                                    -- 用户可见
    intercept       BOOLEAN DEFAULT false,                                   -- 拦截
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_work_order IS '运单工单表';

COMMENT ON COLUMN order_work_order.id IS '主键ID';
COMMENT ON COLUMN order_work_order.tenant_id IS '租户ID';
COMMENT ON COLUMN order_work_order.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_work_order.title IS '标题';
COMMENT ON COLUMN order_work_order.related_no IS '关联单号';
COMMENT ON COLUMN order_work_order.description IS '描述';
COMMENT ON COLUMN order_work_order.followers IS '关注者';
COMMENT ON COLUMN order_work_order.responsible IS '负责人';
COMMENT ON COLUMN order_work_order.remind_time IS '提醒时间';
COMMENT ON COLUMN order_work_order.user_visible IS '用户可见';
COMMENT ON COLUMN order_work_order.intercept IS '拦截';
COMMENT ON COLUMN order_work_order.create_by IS '创建者';
COMMENT ON COLUMN order_work_order.create_time IS '创建时间';
COMMENT ON COLUMN order_work_order.update_by IS '更新者';
COMMENT ON COLUMN order_work_order.update_time IS '更新时间';

CREATE TRIGGER trigger_order_work_order_update_time
    BEFORE UPDATE
    ON order_work_order
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_pod
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    waybill_id      bigint,                                                  -- 关联运单id
    name            text,                                                    -- 名称
    file_name       text,                                                    -- 文件名
    remark          text,                                                    -- 备注
    customer_visible BOOLEAN DEFAULT true,                                   -- 客户可见
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_pod IS '运单POD管理表';

COMMENT ON COLUMN order_pod.id IS '主键ID';
COMMENT ON COLUMN order_pod.tenant_id IS '租户ID';
COMMENT ON COLUMN order_pod.waybill_id IS '关联运单id';
COMMENT ON COLUMN order_pod.name IS '名称';
COMMENT ON COLUMN order_pod.file_name IS '文件名';
COMMENT ON COLUMN order_pod.remark IS '备注';
COMMENT ON COLUMN order_pod.customer_visible IS '客户可见';
COMMENT ON COLUMN order_pod.create_by IS '创建者';
COMMENT ON COLUMN order_pod.create_time IS '创建时间';
COMMENT ON COLUMN order_pod.update_by IS '更新者';
COMMENT ON COLUMN order_pod.update_time IS '更新时间';

CREATE TRIGGER trigger_order_pod_update_time
    BEFORE UPDATE
    ON order_pod
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();


CREATE TABLE IF NOT EXISTS order_service
(
    id              bigint generated by default as identity PRIMARY KEY,   -- 自增主键
    tenant_id       uuid not null,                                           -- 租户ID
    service_name    text,                                                    -- 服务名称
    status          smallint DEFAULT 1,                                      -- 状态：1正常 2停用
    service_code    text,                                                    -- 服务代码
    type            text,                                                    -- 类型
    carrier_type    text,                                                    -- 承运类型
    service_category text,                                                   -- 服务分类
    billing_method  text,                                                    -- 计费方式
    weight_method   text,                                                    -- 计重方式
    bubble_factor   decimal(10,2),                                           -- 计泡系数
    bubble_share    decimal(10,2),                                           -- 分泡比例
    piece_range     text,                                                    -- 件数范围
    print_account   text,                                                    -- 打单账号
    label_type      text,                                                    -- 打印标签类型
    create_by       text DEFAULT 'admin',                                   -- 创建者
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    update_by       text DEFAULT 'admin',                                   -- 更新者
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP   -- 更新时间
);

COMMENT ON TABLE order_service IS '服务表';

COMMENT ON COLUMN order_service.id IS '主键ID';
COMMENT ON COLUMN order_service.tenant_id IS '租户ID';
COMMENT ON COLUMN order_service.service_name IS '服务名称';
COMMENT ON COLUMN order_service.status IS '状态：1正常 2停用';
COMMENT ON COLUMN order_service.service_code IS '服务代码';
COMMENT ON COLUMN order_service.type IS '类型';
COMMENT ON COLUMN order_service.carrier_type IS '承运类型';
COMMENT ON COLUMN order_service.service_category IS '服务分类';
COMMENT ON COLUMN order_service.billing_method IS '计费方式';
COMMENT ON COLUMN order_service.weight_method IS '计重方式';
COMMENT ON COLUMN order_service.bubble_factor IS '计泡系数';
COMMENT ON COLUMN order_service.bubble_share IS '分泡比例';
COMMENT ON COLUMN order_service.piece_range IS '件数范围';
COMMENT ON COLUMN order_service.print_account IS '打单账号';
COMMENT ON COLUMN order_service.label_type IS '打印标签类型';
COMMENT ON COLUMN order_service.create_by IS '创建者';
COMMENT ON COLUMN order_service.create_time IS '创建时间';
COMMENT ON COLUMN order_service.update_by IS '更新者';
COMMENT ON COLUMN order_service.update_time IS '更新时间';

CREATE TRIGGER trigger_order_service_update_time
    BEFORE UPDATE
    ON order_service
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
