import datetime as _dt
import typing as _tp
import zoneinfo as _zi

USA_STATES = _tp.Literal[
    'CT',
    'DE',
    'FL',
    'GA',
    'IN',
    'KY',
    'ME',
    'MD',
    'MA',
    'MI',
    'NH',
    'NJ',
    'NY',
    'NC',
    'OH',
    'PA',
    'RI',
    'SC',
    'VT',
    'VA',
    'WV',
    'AL',
    'AR',
    'IL',
    'IA',
    'KS',
    'LA',
    'MN',
    'MS',
    'MO',
    'NE',
    'ND',
    'OK',
    'SD',
    'TN',
    'TX',
    'WI',
    'AZ',
    'CO',
    'ID',
    'MT',
    'NM',
    'UT',
    'WY',
    'CA',
    'NV',
    'OR',
    'WA',
    'AK',
    'HI',
]


USA_STATE_TIMEZONES: dict[USA_STATES, _dt.tzinfo] = {
    # Eastern Time (UTC-5, with DST)
    'CT': _zi.ZoneInfo('America/New_York'),
    'DE': _zi.ZoneInfo('America/New_York'),
    'FL': _zi.ZoneInfo('America/New_York'),
    'GA': _zi.ZoneInfo('America/New_York'),
    'IN': _zi.ZoneInfo('America/New_York'),
    'KY': _zi.ZoneInfo('America/New_York'),
    'ME': _zi.ZoneInfo('America/New_York'),
    'MD': _zi.ZoneInfo('America/New_York'),
    'MA': _zi.ZoneInfo('America/New_York'),
    'MI': _zi.ZoneInfo('America/New_York'),
    'NH': _zi.ZoneInfo('America/New_York'),
    'NJ': _zi.ZoneInfo('America/New_York'),
    'NY': _zi.ZoneInfo('America/New_York'),
    'NC': _zi.ZoneInfo('America/New_York'),
    'OH': _zi.ZoneInfo('America/New_York'),
    'PA': _zi.ZoneInfo('America/New_York'),
    'RI': _zi.ZoneInfo('America/New_York'),
    'SC': _zi.ZoneInfo('America/New_York'),
    'VT': _zi.ZoneInfo('America/New_York'),
    'VA': _zi.ZoneInfo('America/New_York'),
    'WV': _zi.ZoneInfo('America/New_York'),
    # Central Time (UTC-6, with DST)
    'AL': _zi.ZoneInfo('America/Chicago'),
    'AR': _zi.ZoneInfo('America/Chicago'),
    'IL': _zi.ZoneInfo('America/Chicago'),
    'IA': _zi.ZoneInfo('America/Chicago'),
    'KS': _zi.ZoneInfo('America/Chicago'),
    'LA': _zi.ZoneInfo('America/Chicago'),
    'MN': _zi.ZoneInfo('America/Chicago'),
    'MS': _zi.ZoneInfo('America/Chicago'),
    'MO': _zi.ZoneInfo('America/Chicago'),
    'NE': _zi.ZoneInfo('America/Chicago'),
    'ND': _zi.ZoneInfo('America/Chicago'),
    'OK': _zi.ZoneInfo('America/Chicago'),
    'SD': _zi.ZoneInfo('America/Chicago'),
    'TN': _zi.ZoneInfo('America/Chicago'),
    'TX': _zi.ZoneInfo('America/Chicago'),
    'WI': _zi.ZoneInfo('America/Chicago'),
    # Mountain Time (UTC-7, with DST) – except Arizona
    'AZ': _zi.ZoneInfo('America/Phoenix'),
    'CO': _zi.ZoneInfo('America/Denver'),
    'ID': _zi.ZoneInfo('America/Denver'),
    'MT': _zi.ZoneInfo('America/Denver'),
    'NM': _zi.ZoneInfo('America/Denver'),
    'UT': _zi.ZoneInfo('America/Denver'),
    'WY': _zi.ZoneInfo('America/Denver'),
    # Pacific Time (UTC-8, with DST)
    'CA': _zi.ZoneInfo('America/Los_Angeles'),
    'NV': _zi.ZoneInfo('America/Los_Angeles'),
    'OR': _zi.ZoneInfo('America/Los_Angeles'),
    'WA': _zi.ZoneInfo('America/Los_Angeles'),
    # Alaska Time (UTC-9, with DST)
    'AK': _zi.ZoneInfo('America/Anchorage'),
    # Hawaii-Aleutian Time (UTC-10, no DST)
    'HI': _zi.ZoneInfo('Pacific/Honolulu'),
}
